import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const templates = [
  {
    constName: 'MARKETING_LEAD_NOTIFICATION_TEMPLATE',
    input: 'emails/build/templates/marketing-lead-notification.html'
  },
  {
    constName: 'MARKETING_LEAD_CONFIRMATION_TEMPLATE',
    input: 'emails/build/templates/marketing-lead-confirmation.html'
  }
];

const outputPath = 'src/marketing-leads/email-templates/generated-email-templates.ts';

const lines = [
  '/* This file is generated by `pnpm email:build`. Do not edit manually. */',
  ''
];

for (const template of templates) {
  const html = readFileSync(template.input, 'utf8').trim();
  lines.push(`export const ${template.constName} = ${JSON.stringify(html)};`);
  lines.push('');
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(join(process.cwd(), outputPath), `${lines.join('\n')}\n`);
